efibootmgr: sync with upstream while efivar upgraded to 0.23
Sync with upstream to have the following fix:
...
commit 53aa9cdf7f0746f91f39521d020b024103041384
Author: Peter Jones <pjones@redhat.com>
Date:   Thu Mar 3 09:50:03 2016 -0500

    Explicitly pass a mode to efi_set_variable() in all cases.

    We'll have to do this for efivar-0.24 .

    Signed-off-by: Peter Jones <pjones@redhat.com>
...

It fixed compile failure:
...
efibootmgr.c: In function 'make_boot_var':
efibootmgr.c:305:7: error: too few arguments to function 'efi_set_variable'
  rc = efi_set_variable(boot->guid, boot->name, boot->data,
       ^
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>